config/routes.rb
StateView::Application.routes.draw do
  resources :products

  root :to => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :price

  validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new", status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])    
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html {           
          redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html {           
          render action: "edit",status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def render(*args, &block)
    if request.xhr?
      options = args.extract_options!
      options[:layout] = false
      args.push options
    end
    super
  end

  # def redirect_to(*args, &block)
  #   if request.xhr?
  #     options = args.extract_options!      
  #     unless options[:notice].blank?        
  #       response.headers["state_notice"] = options[:notice]
  #     end
  #     args.push options
  #   end
  #   super
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def r(name, value)
    content_tag(:data, value,  :meta => name )
  end

  def rh(name, value)
    content_tag(:data, nil,  :meta => name, :value => value )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StateView</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= requirejs_include_tag  "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :title %>
  <%= f.input :price %>
  <%= f.button :submit %>
<% end %>

app/views/products/edit.html.erb
<td colspan=5>
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path, :'state-event' => :click, :'state-transcation' => :back %>
</td>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1>Listing products</h1>
      <div class='new_product_display'>
      </div>
      <table class="table product_list">
        <thead>
          <tr>
            <th>标题</th>
            <th>价格</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>        
          <% @products.each do |product| %>
            <tr>
              <td><%=r :title, product.title %><%= rh :id, product.id %></td>
              <td><%=r :price, product.price %></td>
              <td><%= link_to 'Show', product %></td>
              <td><%= link_to 'Edit', edit_product_path(product),  :'state-event' => 'click', :'state-transcation' => :editable %>
              <%#= link_to 'Edit', "##{product.id}/edit" %>

              </td>
              <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>              
            </tr>
          <% end %>
        </tbody>
      </table>

      <br />

      <%= link_to 'New Product', new_product_path, :class => "new_product" %>
    </div>
  </div>
</div>

<script type="text/javascript">
  require(["products", 'backbone', "jquery_ujs"], function(ProductView, Backbone ){    
    product_view = new ProductView({
      new_tag_name : "div",
      new_action_element: $(".new_product"),
      display_new_callback: function(){                    
        $(".new_product_display").html(this.el);
      },
      render_new_callback: function(){                                       
        $("tbody").append(this.el)                          
      }       
    })
    
    $("table>tbody>tr").each(function(i, e){
      product_view.bind_item_view({ el: e })      
    });

    Backbone.history.start();   
  });
</script>

app/views/products/new.html.erb
<div>
	<h1>New product</h1>

	<%= render 'form' %>

	<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
          <td><%=r :title, @product.title %><%= rh :id, @product.id %></td>
          <td><%=r :price, @product.price %></td>
          <td><%= link_to 'Show', @product %></td>
          <td><%= link_to 'Edit', edit_product_path(@product),  :'state-event' => 'click', :'state-transcation' => :editable %>    
          </td>
          <td><%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %></td>